### ISSUE TITLE
language mapping not found by Atom's Hydrogen package

### ISSUE THREAD

**Issue by arsaniwilliam** [abingham/jupyter-elm-kernel#13]
[Hydrogen](https://atom.io/packages/hydrogen) is a jupyter front-end plugin for [Atom](https://atom.io/).  
It fails to execute elm code because the language field in the kernel json is _`text`_ instead of _`elm`_.
We should change that in [install.py](https://github.com/abingham/jupyter-elm-kernel/blob/master/elm_kernel/install.py#L15) to say _`"language":"elm"`_.  
  
In the meantime, I found a  workaround:  
We can create a language mapping in Hydrogen's package settings from _text_ to _elm_ so that it can find the correct kernel for the language. (`Language Mappings: {"text":"elm"}`)

**Comment by abingham** [comment]
Thanks for catching that! A fix is in master. If you agree that it's fixed, please close this.

**Comment by arsaniwilliam** [comment]
Looks great! thank you!
