### ISSUE TITLE
SVG example not woking

### ISSUE THREAD

**Issue by mcoors** [abingham/jupyter-elm-kernel#19]
I get the following error when i try  the SVG example:

> I cannot find module 'Svg'.
> 
> Module 'Main' is trying to import it.
> 
> Potential problems could be:
>   * Misspelled the module name
>   * Need to add a source directory or new dependency to elm-package.json
> 
> 

I am using:
Notebook server version: 5.2.2
Python 3.6.4 on Win64

On first "run" it looks like the core packages getting installed as the error message looks like the following:

> I cannot find module 'Svg'.
> 
> Module 'Main' is trying to import it.
> 
> Potential problems could be:
>   * Misspelled the module name
>   * Need to add a source directory or new dependency to elm-package.json
> Starting downloads...
> 
>   ● elm-lang/html 2.0.0
>   ● elm-lang/virtual-dom 2.0.4
>   ● elm-lang/core 5.1.1
> 
> Packages configured successfully!

**Comment by paitonic** [comment]
The core packages did install but the 'Svg' package was missing from the installed packages as you see, it was 'ignored'.

The thing is that the elm_kernel on pip (you did install it using pip, right?) is behind `master` branch, and therefore the change (https://github.com/abingham/jupyter-elm-kernel/issues/17) to make it work isn't there. 

Reinstalling the kernel using `pip install -e .` command should solve it for you as long as you are on the master.

**Comment by mcoors** [comment]
Reinstalling with` pip install -e . `worked for me. 
Thanx for your help and your quick answer.
