### ISSUE TITLE
elm 0.19 compatibility

### ISSUE THREAD

**Issue by MMesch** [abingham/jupyter-elm-kernel#20]
I am new to elm, but shouldn't the new command be `elm make` instead of `elm-make`?

https://github.com/abingham/jupyter-elm-kernel/blob/master/elm_kernel/kernel.py#L78-L80

**Comment by abingham** [comment]
Probably. There has not been any work to update this to 0.19. Only in the past few days, in fact, have I had a chance to do any Elm programming for quite some time. I likely won't have any real time to devote to this kernel, but I should be able to process PRs if you're interested.
