### ISSUE TITLE
Syntax highlighting is missing ...

### ISSUE THREAD

**Issue by eimfach** [abingham/jupyter-elm-kernel#24]
I am using nteract to write my notebooks. I don't have syntax highlighting in there using the elm-kernel ... I ask myself if this is a task of the kernel module ? I am not experienced with those things...

**Comment by amphitheres** [comment]
Syntax highlighting is not a task of the kernel, the highlighting is done via the frontend. Could you post a screenshot so that we can have a better sense of the issue?

**Comment by eimfach** [comment]
<img width="799" alt="Bildschirmfoto 2020-01-28 um 20 38 34" src="https://user-images.githubusercontent.com/6602910/73298844-61711e00-420e-11ea-8572-a7a45c99337a.png">
