### ISSUE TITLE
What's the status of this project? few errors

### ISSUE THREAD

**Issue by afidegnum** [abingham/jupyter-elm-kernel#27]
Does this project allow to run full elm codes or only partial codes?

actually when i execute the code, it hangs with no output but the hello world example works.

**Comment by abingham** [comment]
> Does this project allow to run full elm codes or only partial codes?

You need to provide a complete program with a `main` function. This can be broken up over several cells, however.

> actually when i execute the code, it hangs with no output but the hello world example works.

It's entirely possible that this project is just broken. I don't support it or plan to fix it, though I'll be happy to process pull requests.

**Comment by amphitheres** [comment]
> It's entirely possible that this project is just broken.

@abingham The project is in good shape. It may not be installed properly however.
