### ISSUE TITLE
How do i import Additional modules?

### ISSUE THREAD

**Issue by afidegnum** [abingham/jupyter-elm-kernel#28]
so far, i tried running jupyter in the project directory but i have no output but when moved to the src directory, i was able to run it but i had issue with external modules not being available. 

when i move elm.json to the src directory too, jupyther hangs during compilation. 

can you please assist?

**Comment by amphitheres** [comment]
Sure, can you describe in detail the steps to reproduce the bug?

**Comment by afidegnum** [comment]
it's been a year now, I'm back to resuming the test project with your illustrious jupyter elm kernel. How do I feed in the elm.json  for the kernel to use?

**Comment by amphitheres** [comment]
To use a custom elm.json file you must add it to the directory containing your notebook. The kernel will link to this file during compilation. Check out the SVG example.

**Comment by afidegnum** [comment]
Thanks, that was quick, 

I noticed it wasn't possible to import an existing file into the notebook. 

I have created Test.elm and exported it using `module Test exposing (..)`

when I ran Jupyter in the same directory, elm complained about the module not found in the package or source directory specified in elm.json. 

can you please advise?

**Comment by amphitheres** [comment]
Right now you can import custom modules by adding the absolute path to your modules to the source-directories list of your `elm.json`.
